extensions = ["sphinx_needs"]

project = "Qorix Engineering Processes Needs"
master_doc = "index"

# --- Cross-project traceability to organisation/governance/ -----------------
# organisation/governance/ (org_req needs) and this needs/ tree are
# deliberately separate Sphinx-needs projects (see the note in the root
# conf.py) — a product need here previously could only cite an org
# requirement in free-text prose (derives_from), never as a real,
# dead-link-checked :links: target, so a renamed/retired org_req id would
# silently stop resolving to anything while every citation kept building
# clean. needs_external_needs closes that: it imports the org project's
# exported needs.json as valid, checked link targets for this project's
# own :links: fields, without merging the two projects into one build.
#
# json_path is generated by CI (.github/workflows/ci-needs.yml) before this
# project builds — it does not exist in the committed tree. base_url below
# is a placeholder; set it to the deployed root-docs URL (see
# .github/workflows/docs.yml's GitHub Pages deployment) once that URL is
# known, so external-need links resolve to a real page instead of a
# relative path that only happens to work locally.
#
# RE-ENABLED. Was disabled after a real end-to-end build showed two
# fatal problems: this project's needs_types didn't recognize
# org_req/risk/problem/change/exception/tool/infra ("Unknown need
# type"), and it didn't recognize their fields either ("Unknown keys in
# external need source"). Both are fixed below — the 7 external types
# are now registered in needs_types (marked "external, imported only"),
# and every field they use is registered in needs_fields, copied from
# root conf.py and kept in sync with it deliberately (see the comment
# there). Re-verified clean with a real `sphinx-build -b html -W` after
# re-enabling, not assumed from static inspection.
needs_external_needs = [
    {
        "base_url": "../../",
        "json_path": "_external_needs/org_needs.json",
        "id_prefix": "",
    }
]

# --- Need types = the pptx "Cluster" (glob/Feat/Comp/Unit -> int/req/arc/des),
# each cross-referenced to the standard process/work-product it corresponds
# to. See ../STANDARDS.md for the full crosswalk and rationale. ---
needs_types = [
    dict(directive="sys", prefix="SYS_", color="#BFD8D2", style="node",
         title="System Requirement — ASPICE SYS.2 / ISO 15288 System Requirements Definition"),
    dict(directive="feat", prefix="FEAT_", color="#FEDCD2", style="node",
         title="Feature / Software Requirement — ASPICE SWE.1 / ISO 15288 Requirements Definition"),
    dict(directive="comp", prefix="COMP_", color="#DF744A", style="node",
         title="Component / Software Architecture — ASPICE SWE.2 / ISO 15288 Architecture Definition"),
    dict(directive="unit", prefix="UNIT_", color="#DCB239", style="node",
         title="Unit / Detailed Design — ASPICE SWE.3 / ISO 15288 Design Definition"),

    # ISO 26262 functional safety chain — not covered by ASPICE or ISO 15288
    # on its own; layered onto the same needs graph so a safety requirement
    # can link straight into the sys/feat/comp/unit chain above.
    dict(directive="sg", prefix="SG_", color="#B71C1C", style="node",
         title="Safety Goal — ISO 26262-3 clause 6 (HARA)"),
    dict(directive="fsr", prefix="FSR_", color="#D32F2F", style="node",
         title="Functional Safety Requirement — ISO 26262-3 clause 8"),
    dict(directive="tsr", prefix="TSR_", color="#E57373", style="node",
         title="Technical Safety Requirement — ISO 26262-4 clause 6 / ISO 26262-6"),

    # Upstream-of-sys needs: raw stakeholder/business/operational needs
    # (Needs/*-needs.rst) that sys requirements are elicited from. Not
    # part of the ASPICE/ISO 15288 requirements-definition chain itself —
    # this is the pre-requirements input layer feeding it. Added because
    # business-needs.rst / operational-needs.rst / stakeholder-needs.rst
    # already use this directive live in this repo; previously
    # unregistered, which made any build touching them fail outright with
    # "Unknown directive type eng_need".
    dict(directive="eng_need", prefix="NEED_", color="#8E9AAF", style="node",
         title="Stakeholder / Business / Operational Need"),

    # ISO 26262-6 Safety User Manual content — the customer-facing safety
    # feature / recommendation / restriction tables previously hand-maintained
    # in Qorix_SafetyUserManual.docx per module. Modeled as needs so each
    # entry traces to the fsr/tsr chain above (:links:) instead of living as
    # unlinked prose in a Word table. Module-specific IDs (e.g. COM_FEA_001)
    # still satisfy needs_id_regex below — the prefix here is just the
    # auto-id default, not enforced per-module.
    dict(directive="safefeat", prefix="SAFEFEAT_", color="#7B1FA2", style="node",
         title="Module Safety Feature — ISO 26262-6 Safety User Manual"),
    dict(directive="rec", prefix="REC_", color="#F57F17", style="node",
         title="Operational Recommendation — ISO 26262-6 Safety User Manual"),
    dict(directive="res", prefix="RES_", color="#EF6C00", style="node",
         title="Operational Restriction — ISO 26262-6 Safety User Manual"),

    # Unit test cases. Previously these only existed as plain Markdown
    # files with a prose "Covers: UNIT_x_001" line — not part of the
    # needs graph at all, so a test case could silently drift from (or
    # never actually cover) the unit it claimed to verify. Registered as
    # a real need type so :links: to a unit id is dead-link-checked like
    # every other link in this graph (ASPICE SWE.4 / ISO 15288 6.4.5
    # System Analysis — verification against the design).
    dict(directive="tc", prefix="TC_", color="#43A047", style="node",
         title="Unit Test Case — ASPICE SWE.4 / ISO 15288 6.4.5"),

    # Component-integration test cases. Previously this layer didn't
    # exist as an artifact at all — the chain jumped straight from unit
    # test to the root-level system/feature test in `integration test/`,
    # with nothing verifying that a component's own units actually work
    # together inside its architecture (ASPICE SWE.5 / ISO 15288 6.4.8
    # System Analysis — verification within the component boundary,
    # below full system integration).
    dict(directive="itc", prefix="ITC_", color="#00897B", style="node",
         title="Component Integration Test Case — ASPICE SWE.5 / ISO 15288 6.4.8"),

    # --- External types, imported only ----------------------------------
    # Nothing in this project ever writes `.. org_req::` etc. directly —
    # these 7 entries exist purely so needs_external_needs (above) can
    # load the root project's org_req/risk/problem/change/exception/tool/
    # infra needs as real, dead-link-checked citations instead of rejecting
    # them with "Unknown need type". Copied verbatim from root conf.py's
    # needs_types; keep the two in sync if either changes.
    dict(directive="org_req", prefix="ORG_", color="#B8003D", style="node",
         title="Organizational Requirement — ISO 26262 Part 2 / "
                "ISO/SAE 21434 Clause 5 / ASPICE org-level / ISO 29119 "
                "org-level / ISO/IEC/IEEE 15288 clause 6.2"),
    dict(directive="risk", prefix="RISK_", color="#B71C1C", style="node",
         title="Organizational or Project Risk"),
    dict(directive="problem", prefix="PRB_", color="#D32F2F", style="node",
         title="Problem Report"),
    dict(directive="change", prefix="CR_", color="#5C6BC0", style="node",
         title="Change Request"),
    dict(directive="exception", prefix="EXC_", color="#8E24AA", style="node",
         title="Tailoring Exception — deviation from the org-level process "
                "described in organisation/governance/framework/process_metamodel"),
    dict(directive="tool", prefix="TOOL_", color="#00838F", style="node",
         title="Qualified Tool — invoked by a CI workflow or pre-commit hook, "
                "per ASPICE SUP.8/SUP.9 tool qualification"),
    dict(directive="infra", prefix="INFRA_", color="#455A64", style="node",
         title="Infrastructure Element — ISO/IEC/IEEE 15288 clause 6.2.2, "
                "outcome (b): infrastructure identified and specified"),
]

# Free-text fields on needs.
# `standard` and `derives_from` are intentionally NOT registered as
# needs_extra_links: elsewhere in this repo (organisation/governance/, governed by
# the root conf.py) derives_from mixes real need ids with external
# standard-clause citations that have no matching need — as a real link
# that would fail needs_report_dead_links. Kept as free text here too, for
# the same reason and for consistency between the two conf.py files, even
# though every derives_from usage actually inside Needs/ today happens to
# cite a real eng_need id.
#
# Closed status vocabulary, kept identical to the constant of the same
# name in root conf.py — see that file's comment for the full rationale
# (needs_statuses is deprecated in this installed sphinx-needs (8.3.1);
# needs_fields.status.schema.enum is the replacement, confirmed by an
# actual -W build).
NEEDS_STATUS_ENUM = [
    "none", "draft", "proposed", "approved", "released", "deprecated",
    "retired", "open", "closed", "resolved",
]

needs_fields = {
    "status": {
        "description": "Need status. Enum enforced via schema, not the "
                        "deprecated needs_statuses config — see "
                        "NEEDS_STATUS_ENUM above.",
        "schema": {"enum": NEEDS_STATUS_ENUM},
        "nullable": True,
    },
    "standard": {
        "description": "Standard/clause this need satisfies",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "derives_from": {
        "description": "Upstream need id or external standard clause this "
                        "requirement derives from (free text — not "
                        "dead-link-checked)",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "kind": {
        "description": "Need classification used by eng_need, e.g. 'need'",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "domain": {
        "description": "Requirement/need domain, e.g. functional, "
                        "operational, business",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "lifecycle_stage": {
        "description": "Lifecycle stage this need belongs to, e.g. "
                        "stakeholder_needs",
        "schema": {"type": "string"},
        "nullable": True,
    },

    # Safety User Manual fields (safefeat / rec / res). Free text, same
    # rationale as `derives_from` above: these frequently cite DFMEA action
    # IDs and other identifiers that live outside the needs graph, so a
    # real link type would trip needs_report_dead_links on legitimate
    # citations.
    "rationale": {
        "description": "safefeat: rationale for claiming safety in this feature",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "use_case": {
        "description": "safefeat: use case for the safety feature",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "dependency": {
        "description": "safefeat: internal or external dependency, if any",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "input_reference": {
        "description": "rec/res: Safety Requirement ID or Safety Analysis "
                        "ID (e.g. a DFMEA action ID) this entry originates "
                        "from",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "req_type": {
        "description": "rec/res: Timing, Execution Sequence, Resource, "
                        "Performance, Implementation, External Dependency, "
                        "Configuration, etc.",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "actions": {
        "description": "rec/res: recommended action for the integrator",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "impact": {
        # Shared with the external `risk` type's "Risk impact" — both are
        # free-text strings, just describing different things (rec/res'
        # non-adherence impact vs. a risk's impact rating). sphinx-needs
        # needs_fields has no per-type namespacing, so one definition
        # covers both; kept the original description since it was here
        # first, not because the risk usage matters less.
        "description": "rec/res: impact of non-adherence to the "
                        "recommended action; also used by the external "
                        "`risk` type as risk impact (from risk-register.yml)",
        "schema": {"type": "string"},
        "nullable": True,
    },

    # --- Fields used only by the external org_req/risk/problem/change/
    # exception/tool/infra types (needs_external_needs, above). Copied
    # verbatim from root conf.py's needs_fields; keep both in sync.
    "likelihood": {
        "description": "Risk likelihood (from risk-register.yml)",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "mitigation": {
        "description": "Risk mitigation plan (from risk-register.yml)",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "affected_needs": {
        "description": "Need IDs a problem/change affects, as recorded in "
                        "problem-register.yml / change-register.yml. Kept "
                        "as free text, not a real link — these ids "
                        "(SWR_*, SYSR_*) are illustrative placeholders used "
                        "elsewhere in the repo (see test/teststrategy/) "
                        "and don't resolve to any actual need, so "
                        "registering this as a needs_extra_links option "
                        "would fail the dead-link gate.",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "pinned": {
        "description": "Whether the tool's version is pinned in CI "
                        "(from tool_register.yml: version_pinned)",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "version": {
        "description": "Two distinct uses, disambiguated by need type: for "
                        "the external `tool` type (imported only, see "
                        "needs_external_needs above), the pinned version "
                        "string when known. For every requirement-shaped "
                        "type native to this project (sys/feat/comp/unit/"
                        "sg/fsr/tsr/eng_need/safefeat/rec/res/tc/itc), a "
                        "baseline content version (currently 1.0.0 on all "
                        "of them, added in the same pass as the `status` "
                        "enum above) — not a tool's version, the "
                        "requirement text's own revision. Kept identical "
                        "to root conf.py's copy.",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "toolchain_step": {
        "description": "build / static_analysis / test_execution / "
                        "traceability (from tool_register.yml)",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "used_in": {
        "description": "Module(s) or project(s) this tool is used in "
                        "(from tool_register.yml)",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "ci_workflow": {
        "description": "Workflow file(s) that invoke this tool "
                        "(from tool_register.yml)",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "tcl": {
        "description": "Tool Confidence Level, ISO 26262-8 clause "
                        "11.4.5-11.4.7 (from tool_register.yml — TBD for "
                        "every tool, no determination made yet)",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "qualification_status": {
        "description": "Tool qualification status (from tool_register.yml)",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "provider": {
        "description": "Who provides/hosts this infrastructure element "
                        "(e.g. GitHub Actions, GitHub Pages, local machine)",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "acquisition": {
        "description": "How this infrastructure element was acquired "
                        "(SaaS subscription, self-hosted, checked-in config "
                        "file, etc.) — ISO/IEC/IEEE 15288 clause 6.2.2 "
                        "outcome (c)",
        "schema": {"type": "string"},
        "nullable": True,
    },
    "availability_note": {
        "description": "What guarantees availability today, and what "
                        "monitors it — ISO/IEC/IEEE 15288 clause 6.2.2 "
                        "outcome (d). Free text; disclose 'none' rather "
                        "than implying monitoring that doesn't exist.",
        "schema": {"type": "string"},
        "nullable": True,
    },
}

# Named link types, additive alongside the default `:links:` field — nothing
# existing is renamed or required to use these. Copied verbatim from
# qorix-ik-main's qik-axon scaffold (rust/qik-axon/templates/needs/conf.py),
# and kept identical to the same block in root conf.py — same rationale:
# align this project's link vocabulary with the org's own tooling. Used so
# far only for the unambiguous ASPICE requirement/architecture/design/test
# chain (feat satisfies sys, comp satisfies feat, unit satisfies comp, tc
# verifies unit, itc verifies comp) — see STANDARDS.md's crosswalk table.
# The ISO 26262 sg/fsr/tsr chain deliberately still uses plain `:links:`;
# which of these verbs is the exact right one there wasn't obvious enough
# to guess, so it's left as a disclosed gap rather than asserted.
needs_links = {
    "derived_from": {"incoming": "gives rise to",     "outgoing": "derived_from"},
    "satisfies":    {"incoming": "is satisfied by",   "outgoing": "satisfies"},
    "fulfils":      {"incoming": "is fulfilled by",   "outgoing": "fulfils"},
    "implements":   {"incoming": "is implemented by", "outgoing": "implements"},
    "verifies":     {"incoming": "is verified by",    "outgoing": "verifies"},
    "belongs_to":   {"incoming": "consists of",       "outgoing": "belongs_to"},
    "consists_of":  {"incoming": "belongs to",        "outgoing": "consists_of"},
}

# (Status enum lives at the top of this file, in NEEDS_STATUS_ENUM /
# needs_fields["status"] — not here as needs_statuses, which this
# installed sphinx-needs treats as deprecated.)

# Every need must declare at least one upstream link via the built-in
# `links` option or one of the named types above (sys <- feat <- comp <-
# unit, sg <- fsr <- tsr). A broken or missing link, or a duplicate id,
# fails the build below with -W.
needs_id_required = True
needs_id_regex = r"^[A-Z]+_[A-Za-z0-9_]+"

# Fail the build (not just warn) on unresolvable need links, e.g. a
# `:links:` field pointing at an id that doesn't exist.
needs_report_dead_links = True

# --- Qorix-branded PDF export (Safety User Manual) -------------------------
# Produces a second, standalone LaTeX/PDF document from just
# communication/safety_user_manual.rst (still resolving :links:/:need:
# cross-references against the full needs graph loaded above), styled to
# match Qorix_SafetyUserManual.docx: cover page, repeating header
# (Config ID / Version / Date), repeating footer (logo + confidentiality
# line + page number), and cyan table header rows.
latex_engine = "xelatex"
latex_table_style = ["booktabs", "colorrows"]
latex_additional_files = [
    "_static/qorix_logo.png",
    "_static/qorix_cover_graphic.png",
]
latex_documents = [
    ("index", "qorixengineeringprocessesneeds.tex",
     "Qorix Engineering Processes Needs", "QORIX GmbH", "manual"),
    ("communication/safety_user_manual", "qorix_module_a_safety_user_manual.tex",
     "Qorix Module A Safety User Manual", "QORIX GmbH", "howto"),
]
latex_elements = {
    "fontpkg": r"""
\usepackage{fontspec}
\setmainfont{Carlito}
""",
    "preamble": r"""
\usepackage{colortbl}
\definecolor{qorixcyan}{HTML}{00FFFF}
\definecolor{qorixblue}{HTML}{3A00F5}
\definecolor{qorixgray}{HTML}{F2F2F2}
\sphinxsetup{
  TableRowColorHeader={HTML}{00FFFF},
  TableRowColorOdd={HTML}{FFFFFF},
  TableRowColorEven={HTML}{FFFFFF}
}
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0.6pt}
\renewcommand{\footrulewidth}{0.6pt}
\fancyhead[L]{\small\qorixconfigid}
\fancyhead[C]{\small\qorixversion}
\fancyhead[R]{\small\qorixdocdate}
\fancyfoot[L]{\raisebox{-0.3\height}{\includegraphics[height=10pt]{qorix_logo.png}}}
\fancyfoot[C]{\small Restricted \& Confidential \textcopyright{}QORIX GmbH}
\fancyfoot[R]{\small\thepage}
% Sphinx's own "howto"/"manual" classes switch to \pagestyle{plain} before
% the table of contents and \pagestyle{normal} right after it,
% unconditionally overriding whatever style was active. Make both of
% those page styles behave exactly like our fancy header/footer (deferred
% to \AtBeginDocument since \ps@fancy itself is only fully defined once
% fancyhdr finishes initializing at \pagestyle{fancy} above).
\AtBeginDocument{\let\ps@plain\ps@fancy\let\ps@normal\ps@fancy}
\newcommand{\qorixconfigid}{<Config ID>}
\newcommand{\qorixversion}{<X.Y.Z>}
\newcommand{\qorixdocdate}{dd-Mmm-YYYY}
\newcommand{\qorixstatus}{Draft}
\newcommand{\qorixpreparedby}{QORIX GmbH}
\newcommand{\qorixpreparedloc}{Germany}
""",
    "maketitle": r"""
\begin{titlepage}
\newgeometry{margin=0cm}
\begin{minipage}[t]{0.62\textwidth}
\vspace{2.2cm}\hspace{1.6cm}
\begin{minipage}{0.85\textwidth}{\LARGE\bfseries\makeatletter\@title\makeatother}\end{minipage}
\end{minipage}%
\begin{minipage}[t]{0.38\textwidth}
\vspace{0pt}\hfill\includegraphics[width=0.9\textwidth]{qorix_cover_graphic.png}
\end{minipage}
\vspace{4cm}\hspace{1.6cm}%
\colorbox{qorixcyan}{\begin{minipage}[t][5.6cm][t]{0.3cm}\mbox{}\end{minipage}}%
\colorbox{qorixgray}{\begin{minipage}[t][5.6cm][t]{11.3cm}
\vspace{0.4cm}\hspace{0.4cm}\begin{minipage}{10.5cm}
\textbf{Prepared By:}\\[4pt]
{\Large\qorixpreparedby}\\[2pt]
\qorixpreparedloc\\[16pt]
\begin{tabular}{@{}ll@{}}
CONFIG ID & : \qorixconfigid \\
VERSION   & : \qorixversion \\
DATE      & : \qorixdocdate \\
STATUS    & : \qorixstatus \\
\end{tabular}
\end{minipage}
\end{minipage}}
\end{titlepage}
\restoregeometry
\tableofcontents
\newpage
""",
}
