#!/usr/bin/env bash
# scripts/sync_org_content.sh
#
# Populates organisation/ from org-processes
# (https://github.com/SwatiDavari/org-processes), which owns this content
# as the single source of truth.
#
# organisation/ is no longer committed to test_repo — see .gitignore. This
# script is what puts it on disk before any build, the same way
# fetch_external_needs.sh populates needs/_external_needs/org_needs.json.
# Run this BEFORE fetch_external_needs.sh or any sphinx-build of the root
# project — both need organisation/governance/ physically present.
#
# 2026-08-21: org-processes is pushed to GitHub and CI is wired up.
# .github/workflows/docs.yml and ci-needs.yml both check out
# SwatiDavari/org-processes (pinned to 'main' by default, or to a specific
# tag via the workflow_dispatch org_processes_ref input) and run this
# script automatically before building. The local-sibling-checkout mode
# below still exists for building locally without waiting on CI — see
# getting_started.rst for the manual steps.
#
# Usage: scripts/sync_org_content.sh [path-to-org-processes]
#   defaults to ../org-processes (sibling checkout, matching the workspace)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${1:-${REPO_ROOT}/../org-processes}"
DEST="${REPO_ROOT}/organisation"

if [[ ! -d "${SRC}" ]]; then
  echo "error: org-processes not found at ${SRC}" >&2
  echo "       pass its path explicitly: scripts/sync_org_content.sh /path/to/org-processes" >&2
  exit 1
fi

rm -rf "${DEST}"
mkdir -p "${DEST}"

copied=0
for dir in common_framework governance infrastructure learning_management strategy testing tools; do
  if [[ -d "${SRC}/${dir}" ]]; then
    cp -r "${SRC}/${dir}" "${DEST}/${dir}"
    copied=$((copied + 1))
  fi
done

if [[ "${copied}" -eq 0 ]]; then
  echo "error: no known governance folders found under ${SRC}" >&2
  echo "       expected one or more of: common_framework governance infrastructure learning_management strategy testing tools" >&2
  exit 1
fi

# 2026-08-21: also sync org-processes' own root index.rst, which is the
# single "Organization" landing page test_repo's root index.rst links to
# (organisation/index) -- it lives at the org-processes repo root, not
# inside any of the folders copied above, so the loop above never picks
# it up on its own.
if [[ -f "${SRC}/index.rst" ]]; then
  cp "${SRC}/index.rst" "${DEST}/index.rst"
else
  echo "error: ${SRC}/index.rst not found -- organisation/index would be" >&2
  echo "       missing, breaking the toctree entry in this repo's index.rst" >&2
  exit 1
fi

# 2026-08-21: also sync org-processes' own known_gaps.rst -- a root-level
# page (same reason as index.rst above: it's not inside any of the
# folders copied by the loop above) that organisation/index.rst's own
# toctree links to.
if [[ -f "${SRC}/known_gaps.rst" ]]; then
  cp "${SRC}/known_gaps.rst" "${DEST}/known_gaps.rst"
fi

echo "-- synced organisation/ from ${SRC} (${copied} folders + root index.rst)"
echo "   organisation/ is gitignored — regenerated by this script, never committed."
