#!/usr/bin/env bash
# scripts/sync_org_content.sh
#
# Populates organisation/ from Org_processes, which owns this content as
# the single source of truth (see qorix-engg.code-workspace, which mounts
# Org_processes as a sibling root next to this repo).
#
# organisation/ is no longer committed to test_repo — see .gitignore. This
# script is what puts it on disk before any build, the same way
# fetch_external_needs.sh populates needs/_external_needs/org_needs.json.
# Run this BEFORE fetch_external_needs.sh or any sphinx-build of the root
# project — both need organisation/governance/ physically present.
#
# KNOWN GAP, disclosed rather than hidden: Org_processes is not yet its own
# pushed git repository (no .git found there as of this change) — there is
# no URL/commit/tag to fetch from CI. This script only supports the local
# sibling-checkout path below. .github/workflows/docs.yml and
# ci-needs.yml have NOT been updated to run this script, because there is
# nothing yet for CI to check out — those CI builds will fail on a missing
# organisation/ the next time they run, until Org_processes is pushed to
# GitHub and both this script and the workflows are updated together to
# pull from there instead of (or in addition to) a local path.
#
# Usage: scripts/sync_org_content.sh [path-to-Org_processes]
#   defaults to ../Org_processes (sibling checkout, matching the workspace)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${1:-${REPO_ROOT}/../Org_processes}"
DEST="${REPO_ROOT}/organisation"

if [[ ! -d "${SRC}" ]]; then
  echo "error: Org_processes not found at ${SRC}" >&2
  echo "       pass its path explicitly: scripts/sync_org_content.sh /path/to/Org_processes" >&2
  exit 1
fi

rm -rf "${DEST}"
mkdir -p "${DEST}"

copied=0
for dir in common_framework governance infrastructure learning_management strategy testing tools; do
  if [[ -d "${SRC}/${dir}" ]]; then
    cp -r "${SRC}/${dir}" "${DEST}/${dir}"
    copied=$((copied + 1))
  fi
done

if [[ "${copied}" -eq 0 ]]; then
  echo "error: no known governance folders found under ${SRC}" >&2
  echo "       expected one or more of: common_framework governance infrastructure learning_management strategy testing tools" >&2
  exit 1
fi

echo "-- synced organisation/ from ${SRC} (${copied} folders)"
echo "   organisation/ is gitignored — regenerated by this script, never committed."
